NUPC-2320 Converted to shared library, but on OS X Sierra, getting error from `import nupic.bindings.engine_internal`:
ImportError: dlopen(/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/nupic/bindings/_engine_internal.so, 2): Library not loaded: libnupic_core.dylib
  Referenced from: /Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/nupic/bindings/_engine_internal.so
  Reason: unsafe use of relative rpath libnupic_core.dylib in /Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/nupic/bindings/_engine_internal.so with restricted binary

In [3]: import nupic.bindings.engine_internal