Fail loudly when Python regions reassign an output
Now if you reassign an output, you'll get:

~~~
TypeError: 'DictReadOnlyWrapper' object does not support item assignment
~~~