Work in Progress. https://github.com/htm-community/nupic.cpp/issues/134
* Moving CircleCI from old 1.x config style (`./circle.yml`) to the
  newer 2.x style (`./.circleci/config.yml`).
* Adding a 2nd job to the existing CircleCI config (Darwin), to try and
  build an ARM64 Docker build.
* Updates to Dockerfile for `nupic.cpp` instead of older `nupic.core`.

With these changes (so far), one can start a local CircleCI build of
NuPIC Docker on ARM64.

We get to our first error (which seems like the kind of error I'd expect going
from `x86_64` -> `arm64`. I have no idea what to do with it, though:

```
[ 63%] Building CXX object src/test/CMakeFiles/unit_tests.dir/unit/ntypes/BasicTypeTest.cpp.o
/usr/local/src/nupic.cpp/src/test/unit/ntypes/BasicTypeTest.cpp:115:49: error: narrowing conversion of '-128' from 'int' to 'nupic::Byte {aka char}' inside { } [-Wnarrowing]
   Byte bufByte[8] = {0, 1, 2, 3, 4, 5, -128, 127};
                                                 ^
src/test/CMakeFiles/unit_tests.dir/build.make:521: recipe for target 'src/test/CMakeFiles/unit_tests.dir/unit/ntypes/BasicTypeTest.cpp.o' failed
make[2]: *** [src/test/CMakeFiles/unit_tests.dir/unit/ntypes/BasicTypeTest.cpp.o] Error 1
CMakeFiles/Makefile2:436: recipe for target 'src/test/CMakeFiles/unit_tests.dir/all' failed
make[1]: *** [src/test/CMakeFiles/unit_tests.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
setup.py: Calling /usr/local/src/nupic.cpp/bindings/py/packaging/setup.py
```